#SPDX-License-Identifier: MIT-0
---
# tasks file for mysql
#SPDX-License-Identifier: MIT-0
# tasks file for mysql
- name: install mysql
  dnf:
    name: mysql-server
    state: present
  #notify: restart mysql
- name: start and enable mysql service
  systemd:
    name: mysqld
    state: started
    enabled: yes
- name: ensure mysql is running
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Create MySQL database
  community.mysql.mysql_db:
    name: appdb
    state: present
  become: yes

- name: Create MySQL database
  community.mysql.mysql_db:
    name: mydb
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
